### ISSUE TITLE
Iterating over an empty array causes infinite recursion

### ISSUE THREAD

**Issue by oeed** [TennyZhuang/iter-chunks#3]
Consider this test:

```rust
#[test]
fn test_empty_iterator() {
    let arr: [bool; 0] = [];
    let mut i = 0;
    let mut chunks = arr.into_iter().chunks(3);

    while let Some(chunk) = chunks.next() {
        for _ in chunk {}
        i += 1;
    }
    assert_eq!(i, 0);
}
```

Intuitively, `chunks.next()` should immediately return `None`. Instead it returns `Some` with an empty chunk. This then requires clunky checking of the chunk/checking the array is empty first then skipping. Perhaps the iterator could peek/hold the first value?

Additionally, it's unintuitive to be required to iterate the entire chunk in order to advance to the next chunk. This crate is great as `itertools`'s `Chunks` isn't `Send`, so thank you!

**Comment by TennyZhuang** [comment]
Thanks for your suggestion! I'll try to fix it ASAP.

**Comment by TennyZhuang** [comment]
> Additionally, it's unintuitive to be required to iterate the entire chunk in order to advance to the next chunk.

I'll check the itertools's behavior.
